# Generated by Django 5.1 on 2024-08-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='my_app/static/images', width_field='width'),
        ),
    ]
