# Generated by Django 5.1 on 2024-08-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_remove_group_height_remove_group_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='placeholder',
            field=models.TextField(default=' ', max_length=100),
        ),
    ]
