# Generated by Django 5.1 on 2024-08-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_group_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='placeholder',
            field=models.CharField(blank=True, default=' ', editable=False, max_length=100, null=True),
        ),
    ]
