# Generated by Django 5.1 on 2024-08-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='description',
            field=models.TextField(default=' ', max_length=40000),
        ),
    ]
